### ISSUE TITLE
Express Rate Limiter

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#1]
**TODO:** Implement an expressJS-compatible rate limiter. 

A rate limiter is a type of middleware that blocks users from repeatedly spamming/flooding the server with requests , an issue that could potentially escalate to a denial of service attack. A rate limiter is definitely not a catch-all solution - there's still a minimal amount of processing needed to block offenders - however, it's still useful in stopping attackers before they ask the server to do something computationally expensive like a database call, password hash, etc. 

I recommend the [express-rate-limit](https://www.npmjs.com/package/express-rate-limit) package. It's very minimalistic but it gets the job done. Feel free to use any other package - or even a better thought-out solution - if you wish, so long as its compatible with our license.

**Comment by zeim839** [comment]
Also, It'd be a good idea to add the following as options for `.env`
```
RATE_LIMIT_MAX = ...
RATE_LIMIT_TIMEOUT = ...
```
Corresponding with:
```js
// From example at https://www.npmjs.com/package/express-rate-limit
const limiter = rateLimit({
        // Violators get limited for RATE_LIMIT_TIMEOUT number of minutes:
	windowMs: RATE_LIMIT_TIMEOUT * 60 * 1000, 

        // Max number of requests per window (time span of windowMs, see line above):
	max: RATE_LIMIT_MAX, 

        // ...
	standardHeaders: true, 
	legacyHeaders: false,
})
```

Then the whole limiter variable can be passed as a value in `config.js`
This example is specific to the [express-rate-limit](https://www.npmjs.com/package/express-rate-limit) but, again, feel free to explore other options.

**Comment by devp4** [comment]
Hi! I would like to work on this

**Comment by zeim839** [comment]
@devp4
Sure, I'll assign you

**Comment by devp4** [comment]
Will every endpoint use the same rate limiter?

**Comment by zeim839** [comment]
Yes.
Our routes are probably going to be very simple, so I don't see why we should set different limits. What do you think?

**Comment by devp4** [comment]
Yeah I was thinking the same. Only time I was thinking of different was during any database querying happening. Maybe allow less requests than, say, visiting the home page.

**Comment by devp4** [comment]
I got to step 6 of the contributing guideline but get this message. 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/76539310/193419936-5f4b4999-71d7-4fda-9009-577c6b07d013.png">

**Comment by zeim839** [comment]
I think you'll need to fork the repository, clone your local fork and then push your changes there. Once you've cloned your fork, you can just copy and paste your current work from one folder to the other. You can learn more about forks [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks).
