### ISSUE TITLE
Create the /blog page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#109]
**TODO**: Create an expanded version of the blogs section of the home screen in `views/blog.js`

**Comment by Brian-Magnuson** [comment]
![image](https://user-images.githubusercontent.com/92892499/219513550-8fa9e846-8ee8-4664-b2db-2362dae7973f.png)

I created a blog-grid.ejs component to make this work. If you pass it a value for `maxItems`, it will display a maximum of that many blog posts. It does not work with images yet.

**Comment by zeim839** [comment]
Can you add an onclick property to each blog entry that redirects to `/blog/ARTICLE_ID`? Article ID is passed via the entry.id variable.

**Comment by Brian-Magnuson** [comment]
![msedge_snHGJqrj2d](https://user-images.githubusercontent.com/92892499/219829861-a6a8b1c7-34ad-493e-858f-18b02ec52201.gif)

I tried doing this as you requested. I think it's correct, but there are 404 errors.

**Comment by zeim839** [comment]
Implemented in #134 
I copied your changes onto a fresh branch and the automated testing issue was resolved. I'll be closing your pull request (#127), but since I've credited you as the commit author your contributions should still count.

Thanks for the help!

**Comment by Brian-Magnuson** [comment]
Nice! Thank you!
