### ISSUE TITLE
Make landing page buttons interactive

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#116]
In the landing page (index.js), hovering over the "become a member" button in the navigation bar triggers an animation. These effects/animations are instrumental in guiding user interaction with the website. The aim of this issue is to program similar animations for the rest of the buttons on the landing page.

**TODO**: Create onHover effects for the rest of the buttons in the landing page. Refer to files `views/index.ejs`, `public/css/common.css`, and `public/css/index.css`. To be clear, only the "become a member" button should feature the slide-up animation (using this for all buttons would be overkill), instead, use your own best judgement to create simple onHover effects.

**Comment by Dinokojt7** [comment]
Hi please assign thanks

**Comment by zeim839** [comment]
Implemented in #117 
Thank you @Dinokojt7
