### ISSUE TITLE
About button should link to #title_animation

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#119]
**Problem:**
the About button in the navigation bar redirects to the `#about` anchor, which no longer exists because the about section was removed.

**TODO:** 
Navigate through the site and ensure that all About buttons link to the `#title_animation` anchor. The first button that comes to mind is in `views/components/navbar.ejs` - but there might be more.

**Comment by vatsalsinghkv** [comment]
Please assign this to me

**Comment by vatsalsinghkv** [comment]
I was wondering what if we add smooth scrolling too? Like when we click `#portfolio` it just snapped into that instead of smooth scrolling.

**Comment by zeim839** [comment]
That sounds like a great idea 👍

**Comment by vatsalsinghkv** [comment]
Please review #121

**Comment by zeim839** [comment]
Implemented in #121 
Thanks @vatsalsinghkv
