### ISSUE TITLE
Implement DELETE button API calls

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#120]
**TODO:**
Navigate to the `/admin` page, the username should be `admin` and the password should be `123456`. If you select the checkboxes from amongst the three tables, a red DELETE button should appear. Write javascript code so that the page sends a HTTP delete request to each of the delete routes defined in the `routes` folder (the images route has not been implemented, so you dont need to do anything for that table). I would also recommend creating a new route that enables mass-deleting of objects by taking an array of IDs as input. 

The selected IDs from the tables are stored in the `blogTableSelections` and `userTableSelections` variables. Any frontend code should go into the `public/js/dashboard.js` file.

**Comment by vatsalsinghkv** [comment]
Please assign this to me

**Comment by zeim839** [comment]
@vatsalsinghkv Any updates?
