### ISSUE TITLE
"SOURCE" buttons should all be at the same height

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#149]
**Preview:**
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/50573884/236656168-25d10979-ae56-4f45-843d-a7fa8c44852b.png">

**Help Wanted:**
The 'source' buttons should always appear at the bottom of each portfolio card, so the button under 'Lunch Buddy' should be at the same vertical position as the other cards. The EJS/html source for the page can be accessed in `views/index.ejs` and its CSS sheet in `public/css/index.css`.

**Comment by Hendriksn** [comment]
I can do that! Could you please assigne me? :)

**Comment by zeim839** [comment]
Yes, @Hendriksn

**Comment by zeim839** [comment]
Implemented in #153
