### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#16]
Task: create Club website navigation bar

Preview:
![navbar](https://user-images.githubusercontent.com/50573884/194962624-aef37140-e5c5-4586-802d-3fdb52604e0d.jpg)

**"UF OSC" title bar:**
Font: Outrun Future (download [here](https://www.dafont.com/outrun-future.font))
Weight: Bold

**About/Portfolio/Blog/Contact text:**
Font: Overpass (download [here](https://fonts.google.com/specimen/Overpass))
Weight: Extra bold

**Become a member button:**
Font: Overpass
Weight: Medium
Background color: Hex #76F936

**Font sizes and height:**
The font sizes in my UX design app don't correspond with what web browsers render, so you'll have to use your own best judgement. Try to keep sizes as relatively close to the preview as you can.

Same for the navbars height. Use your own best judgement.

**Responsiveness:**
The black background should always cover 100% of the screen's width and the navbar elements should spread length-wise to the top right and left corners. However, make sure that the navbar elements stop spreading once the screen width extends past 1200px - meaning the distance between the start of the "UF-OSC" title and the end of the "BECOME A MEMBER" button should never exceed 1200px. 

**Extension:**
If possible, nest the `about, portfolio, blog and become a member` buttons in a hamburger menu that shows up on the top right corner for mobile devices or small screen widths. 

**Notes:**
The nav buttons don't have to point to any actual sites yet. Please code the navbar on a separate `.ejs` file and add any fonts/assets/styles in the `Public` folder. Your stylesheet should be on a separate document - I will reorganize these myself later.

**Comment by willfpearce** [comment]
I'll give a crack at it. Though I've never used ejs before. Can other ejs files references the navbar file as a component?

**Comment by zeim839** [comment]
Yes, they can. Here's the [documentation](https://ejs.co/#docs) (scroll down to 'includes').
Its an isolated component so I don't think you'll need EJS -  just treat it as normal html.

**Comment by willfpearce** [comment]
i have a completed branch but I don't have permissions to push to the repo

**Comment by zeim839** [comment]
You need to push your changes to a fork. Here's how you do that:
1. Fork repository
2. Clone your account's fork
3. `git branch [name of your branch]`
4. `git checkout [name of your branch]`
5. `cp -rf [directory of old clone] [directory of new clone]`
6. (Optional) Delete your old clone
7. Open pull request? (only if you're ready)

**Comment by zeim839** [comment]
Merged in #18
