### ISSUE TITLE
Broken image preview on blog page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#164]
<img width="1234" alt="image" src="https://github.com/ufosc/Club_Website_2/assets/50573884/29574c36-3235-4cb2-bebe-a6fd8029a3c5">

Issue: If a blog post doesn't have an assigned previewImage, the site erroneously renders a bad URL.
Fix: Add a 'default' entry to the [blog model](https://github.com/ufosc/Club_Website_2/blob/main/model/blog.js#L13) that points to some default banner. The default image should be saved in the `public/assets` folder. 

For the default image, use the following:
![osc](https://github.com/ufosc/Club_Website_2/assets/50573884/adf975db-d7e5-4c07-8bb0-b18cf73fb027)

**Comment by Roy404Dev** [comment]
hell no this shit is too hard I give up. bye
