### ISSUE TITLE
Set ALERT component's margin to 0

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#168]
![Image](https://user-images.githubusercontent.com/50573884/254276744-9d361017-6cd8-4387-9ae4-417ac73ab3a5.png)

Solution: Add `margin: 0px;` [here](https://github.com/ufosc/Club_Website_2/blob/main/public/css/common.css#L120)

**Comment by Ankit8848** [comment]
@zeim839 can u assign to me , I can  do this.

**Comment by zeim839** [comment]
@Ankit8848

**Comment by SiddiqulHaque** [comment]
@zeim839 can you elaborate how to reproduce this issue?
