### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#17]
**Todo**: create the footer element

Preview:
![footer](https://user-images.githubusercontent.com/50573884/194986364-6a8010ef-5446-425d-9841-04eefa7179c3.jpg)

**"UF OSC" title text:**
Font: Outrun Future (download [here](https://www.dafont.com/outrun-future.font))
Weight: Bold

**Copyright text:**
Font: Overpass (download [here](https://fonts.google.com/specimen/Overpass))
Weight: Light
Color: black

**Source/license text:**
Font: Overpass
Weight: Medium

**Font sizes and height:**
The font sizes in my UX design app don't correspond with what web browsers render, so you'll have to use your own best judgement. Try to keep sizes as relatively close to the preview as you can.

Same for the footer's height. Use your own best judgement.

**Responsiveness:**
The footer's background (black on top, white bottom) should always cover 100% of the screen's width and the footer elements should spread length-wise to the bottom right and left corners. However, make sure that the navbar elements stop spreading once the screen width extends past 1200px - meaning the distance between the start of the "UF-OSC" title and the end of the last social button should never exceed 1200px. 

**Notes:**
Source is a hyperlink
License AGLP... is also a hyperlink
Social buttons will be exported and provided once this issue is assigned. 
Your buttons/hyperlinks don't have to reference any URLs yet, I'll add these myself later.

Assume the fonts have already been added to the repo (someone else is working on it). All you'll need to do is install the fonts locally and they should appear on your browser. 

Please code the footer on a separate `.ejs` file and add any fonts/assets/styles in the `Public` folder. Your stylesheet should be on a separate document - I will reorganize these myself later.

**Comment by tjcanro** [comment]
I'll work on this

**Comment by zeim839** [comment]
![fb](https://user-images.githubusercontent.com/50573884/195942182-4d8b6cd2-2e5c-4ae7-bd20-e8c8e6f47f5e.png)
![discord](https://user-images.githubusercontent.com/50573884/195942192-803ce0ee-f69e-4f2a-80a0-31075fd7b197.png)
![instagram](https://user-images.githubusercontent.com/50573884/195942208-34072b9d-e839-4e70-9412-948bfeadc372.png)
![github](https://user-images.githubusercontent.com/50573884/195942214-b77c7170-e9be-469f-ac71-fcb4dcde0ab6.png)

**Comment by Brian-Magnuson** [comment]
I'll help with this

**Comment by zeim839** [comment]
Implemented in #40
