### ISSUE TITLE
Clear contact form after submission

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#189]
TODO (help wanted!): The contact form should be cleared and the captcha refreshed after submission. See [public/js/index.js](https://github.com/ufosc/Club_Website_2/blob/main/public/js/index.js) for the relevant source. 

The API for refreshing the captcha widget is documented here: [Turnstile](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#reset-a-widget).

**Comment by Kaleshe** [comment]
Hi could I be assigned to this issue please? @zeim839
