### ISSUE TITLE
Admin dashboard page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#19]
![Edit article](https://user-images.githubusercontent.com/50573884/195466671-01262130-998f-4218-a2dc-a4c1c84d771f.png)

**Comment by zeim839** [comment]
Todo: create blog data row 
Preview:
![row](https://user-images.githubusercontent.com/50573884/195495042-6d6fca85-ba20-4e1d-bd74-bfae7ebcb74c.png)

**Text:**
Font: overpass
Font weight: medium
Download font [here](https://fonts.google.com/specimen/Overpass)
You only need to install fonts locally, don't move them to the repo folders (assume someone's already done this)

**Background:**
color: #DBDBDB;
border: 1px solid #979797;

**Button:**
font: Overpass;
font weight: medium.
background: #161B22;
border-radius: 8px;
Assume it does nothing (this will be added later). You might need to play around with the border radius value because it might differ on browsers.

**Checkbox:**
The Square all the way on the left is a checkbox. You don't need to style this, use browser defaults - as long as they fit in the row. 

**Text length:**
Text that's too long needs to be truncated (add a '...' at the end).You'll need to write a JS function for this.

**Comment by zeim839** [comment]
Todo: Create table view
Preview:
![Slice](https://user-images.githubusercontent.com/50573884/195496212-3179311c-7cad-4580-834d-3e9f6278cc33.png)

Use the same guidelines as in the reply above. Please add a "No Items" message if there are no rows and keep the minimum height quite small (not like the preview).

**Comment by Brian-Magnuson** [comment]
I'll give data row a try.

**Comment by angel1254mc** [comment]
I'll give the table view a try :)

**Comment by zeim839** [comment]
Data row implemented in #20

**Comment by zeim839** [comment]
Table view implemented in #24
