### ISSUE TITLE
Spring 2024: Add new projects to portfolio

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#191]
TODO: Add Spring 2024 projects to website portfolio. OSC tech leads please respond with your project's name, short description (including languages/technologies used), and GitHub URL. You may see the current list of projects at https://ufosc.org/#portfolio

**Comment by kanielv** [comment]
Alarm Clock

Description: A React-Native application that allows users to configure various punishments for not waking up and ways of detecting if a user is awake. Languages: JavaScript. Framework/tools: React-Native, Expo.

URL: https://github.com/ufosc/Alarm-Clock

**Comment by joeliu0999** [comment]
I can add that

**Comment by zeim839** [comment]
@joeliu0999 I’ll assign you to the issue. We still need info from osc-distro. Maybe you can copy the description from their GitHub page?

**Comment by joeliu0999** [comment]
yeah. I can do that. As of right now, they have nothing though.

**Comment by zeim839** [comment]
@joeliu0999 I asked on Discord and this is what they said: "An OSC themed Linux Distribution based on Debian using Linux From Scratch."

**Comment by joeliu0999** [comment]
@zeim839 cool I will work on it today. Is there out dated project to delete?

**Comment by zeim839** [comment]
Yes, please remove "OSC Website" and "API Group".
The website will continue to be maintained, but its not an active project anymore.

**Comment by zeim839** [comment]
Done. Thanks @joeliu0999
