### ISSUE TITLE
Navbar hamburger menu

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#25]
**Todo:** 
Our current navbar starts to break when the screen width is less than ~640px. We'll need to create a collapsed hamburger menu for mobile devices. You'll need to set up CSS to hide the page titles and instead show a menu for screen widths of less than 640px. Also, you'll need to write javascript to show and hide the collapsed navigation bar whenever the menu is clicked.

**Preview**
For reference, this is what the navbar currently looks like:
![demo](https://user-images.githubusercontent.com/50573884/195962069-d71f9563-a4a0-4b3f-9900-a6d69b7afef1.png)

And this is what the navbar should look like for small screens and mobile devices:
![mobile navbar](https://user-images.githubusercontent.com/50573884/195961693-5ba3fc0f-a726-4120-a646-9f9b07c858c4.png)

When the user clicks on the menu, the collapsed navigation menu should show up like so:
![menu](https://user-images.githubusercontent.com/50573884/195961753-4242c29b-2e6c-45a9-96f8-5bae6cfa64f3.png)

**Description:**

Page text:
All caps.
font: Overpass
font weight: medium
color: #FFFFFF
letter-spacing: 0
Font size should be significantly smaller than the current navbar texts.

Divider line:
Color: #C2C2C4

Hamburger menu image:
![hamburger menu](https://user-images.githubusercontent.com/50573884/195961966-c4bac6c4-3933-40b9-bd5d-c836e880b38a.png)
(Image is all white, if you can't see it, then download the image [here](https://user-images.githubusercontent.com/50573884/195961966-c4bac6c4-3933-40b9-bd5d-c836e880b38a.png))

Adjust sizes, heights, etc. using your own best judgement - try to make it as close to the reference images as possible. Add all new CSS files to the `public/css` folder, add the image file to `public/assets` and any javascript to `public/js` (create these folders if you need to). Feel free to reach out for more clarification or help.

**Comment by zeim839** [comment]
@amitanshusahu I really liked your previous work. Would you like to work on this?

**Comment by amitanshusahu** [comment]
😺 yeah , sure @zeim839

**Comment by zeim839** [comment]
Implemented in #27
