### ISSUE TITLE
Finalize Admin page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#31]
TODO: Finalize admin page. Create a new page `dashboard.ejs`, add the navbar component and use the table component and rows to put the page together. 

The table and row-data components are specific to the blog table data format, you'll need to either modify or create copies of both elements to reproduce the users table. You can ignore the 'delete' button for the time being. 

![admin page](https://user-images.githubusercontent.com/50573884/196725736-fd6ee89c-ebc6-40e5-be2e-d96b20449525.png)

**Comment by amitanshusahu** [comment]
@zeim839, can i work on this 😄

**Comment by zeim839** [comment]
Sorry @amitanshusahu, this is already being worked on. I will post new issues and tag you in a few days.

**Comment by zeim839** [comment]
### Finished. 
Thanks to everyone who contributed.
