### ISSUE TITLE
Add checkbox functionality

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#32]
**Todo**: implement table checkbox functionality. We basically need a global variable to hold a JSON object of all the rows that have been selected. This can be done by passing an onclick attribute to the `data-row.ejs` component:
```ejs
<tr class="data-row">
    <!-- ADD onclick component to the input checkbox element: -->
    <td><input type="checkbox" name="row-selected"/></td>
    <td><%= title %></td>
    <td><%= content %></td>
    <td><%= date %></td>
    <td><%= status %></td>
    <td><%= author %></td>
    <td><button type="button">EDIT</button></td>
</tr>
```
You'll also need to figure out a way to pass an id prop to the element.
Navigate to the `localhost:3000/preview`

**Comment by zeim839** [comment]
@willfpearce, I'll assign you to the issue.

> Would the selection just be used for deleting rows?

Yes, though you don't have to worry about that until we set up a database.  

You can use the `temporary.ejs` file for your implementation. Here's how it should be done:
```ejs
<!-- In temporary.ejs -->
<head>
        <!-- ... -->
        <script>
               // Set up a JSON object to keep track of which post IDs were selected
              var blogTableSelections = {
                      blogPostId: true/false
               }
        </script>
</head>
```

In `data-row.ejs`:
Since `data-row` will be in the same DOM as blogTableSelections, you'll be able to globally access the blogTableSelections variable. 
You'll need to set up an on-select (or on-click) function on the checkbox element here:
```ejs
<td><input type="checkbox" name="row-selected"/></td>
```
That updates the blogTableSelections function with the ID of the data row and whether it's true/false. If a blog post hasn't been selected, then you don't have to make a `false` entry in the blogTableSelections variable - as a matter of fact you can outright delete unselected entries from the object, but only if its convenient.

You'll also need to create an EJS option where we can pass in a blog post ID to the onclick function so we know what's being selected. You don't need to manually create IDs for each element, these will be sourced from the database - we just need a method that collects a JSON object of all the IDs that will be deleted. 

Let me know if you need any further clarification.

**Comment by willfpearce** [comment]
Why not make an array of selected id's?

**Comment by zeim839** [comment]
On secone thought, arrays would be better. I didnt want to use arrays because that would mean that each select/deselect operation would have to search the whole array for the element - as opposed to constant access time with JSON objects. But its not like we're dealing with massive amounts of data so it doesnt really matter really.

**Comment by willfpearce** [comment]
how would we go about giving IDs to the data-rows? Wouldn't they need match the IDs in the database? If so, should I just use temporary, made-up IDs?
