### ISSUE TITLE
Research and set up a markdown parser

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#34]
Todo: our blog posts will be written in markdown (same as github posts/issues) and then parsed and rendered as HTML pages. We'll need to research a markdown parser so we can do this programatically. 

Research markdown-to-HTML node modules and then install and set up a minimal example. Make sure its markdown-to-HTML instead of HTML-to-markdown. 

Here's one I found: https://www.npmjs.com/package/node-html-markdown

**Comment by r0hanshah** [comment]
var showdown  = require('showdown'),
    converter = new showdown.Converter(),
    text      = '# hello, markdown!',
    html      = converter.makeHtml(text);

    console.log(html)

**Comment by r0hanshah** [comment]
npm install showdown

**Comment by zeim839** [comment]
Thanks @r0hanshah, I'll try it out
