### ISSUE TITLE
Set up EJS linting

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#35]
**Todo:** Set up an EJS linter. This is an easy way to automatically style all our html/EJS code and provide more meaningful error messages for EJS (the ejs module is designed to be minimal so they don't serve detailed errors without a linter). 

Here is the module: https://www.npmjs.com/package/ejs-lint

You'll then need to add the linting and testing commands to `package.json`:
```json
  "scripts": {
    "start": "nodemon app.js",
    "test": "standard",
    "lint": "standard && YOUR_TEST_CMD_HERE" ,
    "fix": "standard --fix && YOUR_AUTO_LINT_CMD_HERE"
  },
```

**Comment by willfpearce** [comment]
❗
