### ISSUE TITLE
Set up testing framework

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#36]
TODO: Set up a mocha and chai testing framework. You don't need to write any unit tests, just set up the dependencies and create a `test` folder in the project's root directory.

See a guide on getting started with chai and mocha [here](https://www.testim.io/blog/getesting-with-mocha-and-chai/)
See mocha documentation [here](https://mochajs.org/)
See chai documentation [here](https://www.chaijs.com/)

**Comment by danielwildsmith** [comment]
I will work on this

**Comment by zeim839** [comment]
Implemented in #41
