### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by danielwildsmith** [ufosc/Club_Website_2#37]
Todo: create about section
Preview: 
![Screenshot (42)](https://user-images.githubusercontent.com/92833122/196813895-86b103e2-4552-4e8d-9bd5-0569ac38d1f0.png)

**Text:**
Font: overpass
Font weight: medium
"With the mission to promote, support, and create open-source software, the Open Source Club strives to create a powerful developer community at the University of Florida to accelerate and advance the worldwide open-source community."

**Image:**
Download it [here](https://avatars.githubusercontent.com/u/16708767?s=200&v=4)

**Comment by amitanshusahu** [comment]
@danielwildsmith, i would like to work on this 😄
