### ISSUE TITLE
Discussion: Landing page design

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#47]
Draft: 
![draft](https://user-images.githubusercontent.com/50573884/198691751-ca14bf6a-7c94-49ac-a0bc-6f92c5f415c1.png)

**Comment by Brian-Magnuson** [comment]
I think it's good. Fits with what's been done so far and has nice colors. Though I do wonder, is this the "style" of OSC? I'm not too familiar with OSC's typical "style"

**Comment by tjcanro** [comment]
I'll work on the contact section

**Comment by zeim839** [comment]
@amitanshusahu Hey, would you like to work on the `PORTFOLIO` section? You can make your changes in index.ejs and I'll merge them with everyone else's work. The fonts are:

```
Rounded rectangle title: Overpass, weight: bold
Rounded rectangle text: Overpass, weight: regular
Button font: Overpass, weight: regular (ALL CAPS)
Paragraph text: Overpass, weight: regular
```

Also notice that the Schedule Helper rectangle fades off on the right. You'll have to implement a horizontal scroll view. The fade effect is an element with a black and invisible background color gradient.

**Comment by willfpearce** [comment]
I think the central column is a little bit narrow other than that it looks great.

**Comment by Brian-Magnuson** [comment]
I'll work on the blue box in the 'about' section

**Comment by amitanshusahu** [comment]
> @amitanshusahu Hey, would you like to work on the `PORTFOLIO` section? You can make your changes in index.ejs and I'll merge them with everyone else's work. The fonts are:
> 
> ```
> Rounded rectangle title: Overpass, weight: bold
> Rounded rectangle text: Overpass, weight: regular
> Button font: Overpass, weight: regular (ALL CAPS)
> Paragraph text: Overpass, weight: regular
> ```
> 
> Also notice that the Schedule Helper rectangle fades off on the right. You'll have to implement a horizontal scroll view. The fade effect is an element with a black and invisible background color gradient.

@zeim839  , sure 😄

**Comment by RyanMachado** [comment]
I want to work on the become a member section.

**Comment by zeim839** [comment]
Images for the `BECOME A MEMBER` section:
![cash](https://user-images.githubusercontent.com/50573884/198730587-ad936a6c-80a3-40a1-9248-86c9fb097332.png)
![door](https://user-images.githubusercontent.com/50573884/198730595-6ddca9d8-2c05-400e-9edf-eea01dd2dd0a.png)
![time](https://user-images.githubusercontent.com/50573884/198730606-9f5cae28-d0eb-4937-8c61-11d17b317ee5.png)
![schedule](https://user-images.githubusercontent.com/50573884/198730617-2fc92c06-f6ea-4174-b6a1-61c56d3fb57a.png)

@RyanMachado

**Comment by zeim839** [comment]
# UPDATE
Finished about section.
Thanks @Brian-Magnuson 

Preview:

https://user-images.githubusercontent.com/50573884/198853615-a0ab953b-17ee-4d06-b376-100bdfe8c8c7.mov

**Comment by amitanshusahu** [comment]
> # UPDATE
> 
> Finished about section. Thanks @Brian-Magnuson
@zeim839  @Brian-Magnuson 
### this his how the index.js looks in my pc 👇🏻 
![image](https://user-images.githubusercontent.com/83657737/198871301-04607190-1cad-4657-929d-267bf678d058.png)

### this can be corrected by :- 
``` css
footer{
    position:static;
}
```
### final result 👇🏻 
![image](https://user-images.githubusercontent.com/83657737/198871916-aaefdcda-6a7a-43b6-ba00-d29886c428f5.png)

**Comment by zeim839** [comment]
Thanks, i've created an issue to address the problem.

**Comment by zeim839** [comment]
# UPDATE 2
Added blog section
Added portfolio section
Thanks to everyone who contributed

**Comment by zeim839** [comment]
Finished implementing landing page
