### ISSUE TITLE
Display login errors instead of redirecting

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#53]
Currently, when a user enters an incorrect username or password in the /admin login route, the login form redirects to the /auth/login route and displays the JSON output as a separate page. 

For example:
<img width="532" alt="Screenshot 2022-10-29 at 3 25 08 PM" src="https://user-images.githubusercontent.com/50573884/198849298-e3f108ec-e55a-4db2-b7be-03b69f4ea870.png">

**Todo:** add error message functionality to the login page. This should just be a red text that displays whatever error is returned by the form route. 

This might be possible via an output html tag that can be added to the form (see [this article](https://www.geeksforgeeks.org/html-output-form-attribute/)), but I'm not sure whether you can use this to parse the error message out of the JSON response object. 

Alternatively, we can program the backend to redirect the user back to the login page, except we pass an EJS error variable when we do so.

**Comment by devp4** [comment]
I would like to try this

**Comment by zeim839** [comment]
Go for it. @devp4
