### ISSUE TITLE
Footer links should open in new tab

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#55]
Clicking on hyperlinks in the navbar opens pages in the current tab, thus navigating away from the site. They should instead open in a new tab.

**Comment by Myrfion** [comment]
Hello, I know how to implement this thing, could I take it?

**Comment by zeim839** [comment]
@Myrfion Yes, go for it

**Comment by zeim839** [comment]
Resolved in #57 
Thanks @Myrfion
