### ISSUE TITLE
Admin login page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#6]
TODO: Create a `login.ejs` page for admins to log in with. 

Create an HTML/CSS page containing an HTML login form and save it as `login.ejs` under the `views` folder. If the `.ejs` file format is confusing for you, then don't worry - you can assume it's the same as `.html`. This won't be a public-facing site so I'm not worried about design, you can use your own best judgement as long as the form is right in the middle of the page. 

If you use a CSS stylesheet then please save your file as `login.css` under the `Public` folder (you can create it if it doesn't exist). I strongly advise against using any javascript. 

**Extension:**
Create a new `.env` option under `config.js` for configuring the address of the site. Many vulnerability analysis bots are programmed to automatically check common entry points like `www.mysite.com/login` or `www.mysite.com/admin`, so I recommend adding the option to configure a custom page name for the site. For reference, the name will be passed to `app.js` like so:
```js
app.get(`/${config.login_page}`, (req, res) => {
  // Process request...
})
```
(if you're unwilling or unable to do the extension you can still work on the issue, just let me know and I'll assign it to someone else)

**Comment by amitanshusahu** [comment]
### i would like to work in that i have done similar projects
project links :- 
> StudyBuddy : https://github.com/amitanshusahu/Studdy-Buddy  
>medikets : https://github.com/amitanshusahu/medkets-web

so let me help.. 😄

**Comment by zeim839** [comment]
Sure, go ahead.
@amitanshusahu

**Comment by amitanshusahu** [comment]
### the login page looks good .. 
> check fork : https://github.com/amitanshusahu/Club_Website_2/tree/fix-6
### have a look ..
![image](https://user-images.githubusercontent.com/83657737/193230744-0f66e6ab-91e5-46a1-8766-5cd1a6e64060.png)

### request : -
i will make a pull request tomorrow , it will get count in the hacktoctober fest 😄  , if urgent then i must make a PR today, just update me about that.. 😅

**Comment by amitanshusahu** [comment]
### @zeim839 ,  I recommend you to register in #hacktoberfest2022 as a project maintainer
> https://hacktoberfest.com

so that more people can contribute to the project , taking part in the fest

**Comment by zeim839** [comment]
![Slice](https://user-images.githubusercontent.com/50573884/193299495-20354601-21c2-473d-a3b3-39ce7ce8299f.png)

Hey, thanks for contributing. Would you be willing to modify your existing work to look more like the picture? 
Also, we don't need a `Don't have an account?` prompt (this is an admin login, users will be managed internally). 

Here's some of the CSS for your convenience:

**Main login frame (the div behind the username/password fields):**
```css
background: #FFFFFF;
/* Multiple borders: */
border: 1px solid #F0F0F0;
border: 1px solid #EAEAEA;
box-shadow: 0 2px 4px 0 #C2C1C1;
```
You'll have to implement multiple borders, you can refer to how to do that [here](https://css-tricks.com/snippets/css/multiple-borders/)


**Username/password fields:**
```css
background: #FBFBFB;
/* Again, multiple borders (you'll need to find a way to implement both of these) */
border: 1px solid #E7E7E7;
border: 4px solid #EAEAEA;
```

**Website background color:**
```css
background: #F1F1F1;
```

**Text:**
```css
font-family: Arial-BoldMT;
font-size: XX px;
color: #97918F;
letter-spacing: 0;
```
My design uses `22px` as the font size, but I assume this will be way too large on HTML. Please play around with the font size and get something that looks similar to the picture.

**Comment by zeim839** [comment]
Alright, sounds good. I saw your previous message about hacktoberfest, I'll discuss with my team and see If we want to take part.

**Comment by zeim839** [comment]
Merged. Thanks for the help 👍

**Comment by amitanshusahu** [comment]
i noticed you don't use semicolons in your code, i read about this on a article today
 - https://www.freecodecamp.org/news/lets-talk-about-semicolons-in-javascript-f1fe08ab4e53/  
 
it shows how not using semicolons can cause bugs.. hope this helps 😄

**Comment by RavishGupta** [comment]
Can you please assign me this

**Comment by zeim839** [comment]
@RavishGupta This is a closed issue. It has already been fixed.

**Comment by RavishGupta** [comment]
Okay can you assign me some other issue

**Comment by zeim839** [comment]
Look through the issues page and find something that you like that hasnt already been assigned. Then, reply to the thread asking to be assigned.
