### ISSUE TITLE
Make about rectangle responsive

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#63]
Currently, the about rectangle breaks on small-width mobile displays.
<img width="320" alt="Screenshot 2022-11-01 at 12 40 12 PM" src="https://user-images.githubusercontent.com/50573884/199288091-b90e71c6-3d53-4176-a320-e66b19aa1084.png">

In this task, you'll need to add responsiveness and rearrange the rectangle's elements column-wise:
![responsive](https://user-images.githubusercontent.com/50573884/199288213-446ef106-4a3b-4b54-9818-de82b2537f6d.png)

You might need to remove the shadow-effect trapezium at the bottom of the rectangle if it looks weird on small displays.

**Comment by sam4rano** [comment]
I can work around it if you don't mind

**Comment by zeim839** [comment]
@sam4rano go for it

**Comment by zeim839** [comment]
@sam4rano Any updates?

**Comment by Brian-Magnuson** [comment]
I'll give this a shot

**Comment by zeim839** [comment]
Implemented in #91 
Thanks @Brian-Magnuson!
