### ISSUE TITLE
Add a version parameter to the footer component

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#66]
**TODO:** Create a parameter in the footer component that takes and displays a version string. 

Preview:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/50573884/199523031-d5222374-afb4-45f7-bdb1-27f811311aac.png">

See the 'source' hyperlink at the bottom left. Currently, we're only displaying 'source,' you should pass the parameter into the source string so that it displays as 'Source [VERSION STRING]'

**Comment by r0hanshah** [comment]
working on this

**Comment by zeim839** [comment]
@r0hanshah I think @nickv779 is already working on this.

**Comment by zeim839** [comment]
Implemented in #94
