### ISSUE TITLE
Create Article page component

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#67]
TODO: Create an EJS component to represent article pages. 

Preview:
![article](https://user-images.githubusercontent.com/50573884/199594305-9d83a54a-e697-4e0c-98a0-4c3a931bd105.png)

The component should take the following parameters:
1. Article title
2. Article date
3. Article author
4. Article subheading
5. Article content
6. Article banner

The banner should appear as the full-width image below the header. You can configure the banner to zoom/scale in order to fit into its container using the `object-fit` property, but it should not stretch or distort the image. The rest of the parameters should be placed in their respective locations as well (i.e. the title parameter is shown as the article title, etc.).

Title:
```
Font-family: 'Overpass-Bold'
color: black
```

Date/author:
```
Font: overpass
weight: medium
color: black
```

Subtitle:
```
font: overpass
weight: medium
color: #6A6A6A
```

Content:
```
font: overpass
weight: regular
color: black
```

Scale the fonts as you like, just as long as they look relatively similar to the preview image.

**Comment by willfpearce** [comment]
I can work on this

**Comment by willfpearce** [comment]
#79
