### ISSUE TITLE
Create images table in admin page

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#68]
TODO: Create an images table in the admin page. 

The admin page is defined in `views/admin.ejs` and the two previous tables are defined in `views/components/blog-table.ejs` and `views/components/users-table.ejs`. You can copy the previous two tables for your solution. 

The new images table should be placed between the blog and users tables and should have its own header called 'Images.' 
You can access the admin page by going to the `/admin` route on your browser. The test credentials are 
```
username: admin
password: 123456
```

Also make sure to set up the checkbox mechanism - you can copy the implementation from the other 2 tables. 

Here are the headings for the table, from left to right:
1. Checkbox
2. Name
3. Path
4. Description
5. Date Added

**Comment by Brian-Magnuson** [comment]
I'll give this a try
