### ISSUE TITLE
Create blog API route

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#69]
TODO: Create express routes for interacting with blog articles in the database.

### Blog GET Route:
```js
app.get('/api/blog/:id', (req, res) => {
  // TODO: Return JSON object with blog data for the specified blog ID.
  // or return an error if the ID doesnt exist. 
  // You can access the requested id via req.params.id
})
```
The get route should return the following:
```
id, title, status, previewImg, content, author, date
```
You can access these via the blog model defined in `models/blog.js`. Refer to the mongoose [docs](https://mongoosejs.com/docs/guide.html) for more help. 

### Blog DELETE Route:
```js
app.delete('/api/blog/:id', (req, res) => {
  // TODO: delete the article with specified id. 
  // or return an error if the ID doesnt exist. 
  // You can access the requested id via req.params.id
})
```
You'll need to make sure this route is authenticated. Non-logged in users should receive a 401 Unauthorized error.

### Blog EDIT Route:
```js
app.put('/api/blog/:id', (req, res) => {
  // New data will be passed in via the req.body JSON object.
  // Edit the article with the specified ID according to the provided data in req.body.
})
```
You'll need to make sure this route is authenticated. Non-logged in users should receive a 401 Unauthorized error.

This should be implemented in the 'app.js' file.

**Comment by zeim839** [comment]
Assigned to @devp4

**Comment by willfpearce** [comment]
I can implement this and the users route

**Comment by zeim839** [comment]
@willfpearce Do the users route for now

**Comment by willfpearce** [comment]
Sounds good
