### ISSUE TITLE
Implement in-page href in navbar

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#70]
TODO: Instead of the navbar buttons redirecting to separate sites, they should redirect to the different sections of the page. This can be done by referencing #section-name. For example: if the homepage is `http://localhost:8000/`, then the about section can be reached by redirecting to `http://localhost:8000/#about`. 

You can refer to this [article](https://linuxhint.com/link-specific-part-of-page-with-html/) for more information.

**Comment by lwsm99** [comment]
Hi, can I work on this issue?

**Comment by zeim839** [comment]
@lwsm99 Sorry, this issue has already been solved.

**Comment by zeim839** [comment]
Implemented in #77
