### ISSUE TITLE
Make blog section responsive

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#78]
TODO: Make blog section responsive.

This should be done for two separate generic screen views. 
For tablets, the blog section should look like this:
<img width="522" alt="Screenshot 2022-11-04 at 11 17 27 AM" src="https://user-images.githubusercontent.com/50573884/200010996-a98af3fa-c492-4e0d-a8fd-f35e98843717.png">

Whereas for much smaller mobile devices, it should look like this:
<img width="210" alt="Screenshot 2022-11-04 at 11 21 08 AM" src="https://user-images.githubusercontent.com/50573884/200011624-66a6e7a5-3a30-46bc-bd62-c5b756f833c0.png">

**Comment by danielwildsmith** [comment]
I'd like to work on this

**Comment by zeim839** [comment]
Implemented in #93
