### ISSUE TITLE
Add edit button to users table

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#81]
TODO: Add an edit header and edit button to the users table. 

<img width="634" alt="Screenshot 2022-11-06 at 2 42 40 PM" src="https://user-images.githubusercontent.com/50573884/200191569-83977201-c137-4261-b59a-d15d65d84624.png">

You should be able to copy the implementation from `views/components/blog-table.ejs`

**Comment by lak2611** [comment]
![image](https://user-images.githubusercontent.com/44541211/200226916-afcdb636-5a2a-44f2-90f2-258eee27e3a7.png)

@zeim839 is it ok?

**Comment by zeim839** [comment]
Yes, that's exactly what we want.

**Comment by lak2611** [comment]
@zeim839 how can I push my code in new branch to the repo
![image](https://user-images.githubusercontent.com/44541211/200353323-cf92dd73-890b-4af7-9ffc-8c62475c67e0.png)

**Comment by zeim839** [comment]
You have to clone the project, push to your clone and then create a pull request.
Please familiarize yourself with the [contributing guide](https://github.com/ufosc/Club_Website_2/blob/main/CONTRIBUTING.md)

**Comment by lak2611** [comment]
I've read the contributing guide and cloned the project before by command: git clone https://github.com/ufosc/Club_Website_2.git

Do I need to fork this repo?

**Comment by lak2611** [comment]
@zeim839 
Okay i got it, I created a pull request #84
