### ISSUE TITLE
Add admin page delete button functionality

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#87]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/50573884/200877816-86f7fd05-0a6d-4357-8738-ff95e5cef4b6.png">

TODO: Implement the delete button in `views/admin.ejs`. The button should be hidden, but should appear whenever at least 1 checkbox has been selected. Make sure the button disappears whenever said checkboxes get deleted.

You can access the admin page at `http://localhost:3000/admin`. The username/password is (usually) `admin` and `123456`, respectively. If you are having credential issues, run `node seed.js` to restore the database. 

A separate button should appear for each of the three tables: blog, users, images.

**Comment by willfpearce** [comment]
I'm working on edit button functionality right now fyi
