### ISSUE TITLE
Bug: portfolio section not scrolling the entirety of width

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#95]
**TODO:** Fix bug

**Steps to reproduce issue:**
Reduce screen width to ~480px, scroll down to the "portfolio" section, click the right arrow button 2 or 3 times. The portfolio section will not scroll all the way to the right.

**Comment by adrianmarinwork** [comment]
Do you want me to take a look?

**Comment by zeim839** [comment]
@adrianmarinwork Sure, I'll assign you to the issue.

**Comment by adrianmarinwork** [comment]
I have created a pull request with the solution.

**Comment by zeim839** [comment]
Implemented in #97
Thanks @adrianmarinwork
