### ISSUE TITLE
Make contact section responsive

### ISSUE THREAD

**Issue by zeim839** [ufosc/Club_Website_2#99]
**TODO:** Make homepage contact section responsive. 

For devices under 600px width, the contact form grid should be split into two rows: one containing the form and another containing the text. The text should precede the form - you can do this by manually changing the text and form row placement with `grid-row: ...;`

**Comment by jinitsuga** [comment]
Hello! I can tackle this.

**Comment by zeim839** [comment]
@jinitsuga Go for it

**Comment by zeim839** [comment]
Implemented in #100 
Thanks @jinitsuga
